# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='added_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
