# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_lang', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('added_by', models.CharField(blank=True, max_length=100)),
                ('added_on', models.DateTimeField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('deactivated_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programming_languages',
            },
        ),
    ]
