# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='added_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='added_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='deactivated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='deactivated_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='icno_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='updated_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
