# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_languages', '0003_auto_20170729_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='deactivated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='icno_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
