# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming_languages', '0004_auto_20170729_0029'),
    ]

    operations = [
        migrations.RenameField('ProgrammingLanguage', 'icno_url', 'icon_url'),
    ]
